//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GF.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutoReplenishment
    {
        public int CustomerID { get; set; }
        public string MaterialNumber { get; set; }
        public bool AutoReplenishment1 { get; set; }
        public int ReplenishmentThreshold { get; set; }
        public int ReorderAmount { get; set; }
    }
}
