//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GF.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GFDBEntities : DbContext
    {
        public GFDBEntities()
            : base("name=GFDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AutoReplenishment> AutoReplenishments { get; set; }
        public DbSet<MaterialAvailability> MaterialAvailabilities { get; set; }
        public DbSet<OrderRoll> OrderRolls { get; set; }
    }
}
