//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GF.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialAvailability
    {
        public string MaterialNumber { get; set; }
        public int QuanityInStock { get; set; }
        public int RollWeight { get; set; }
    }
}
