//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GF.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderRoll
    {
        public int CutomerID { get; set; }
        public string GlatfelterOrderNumber { get; set; }
        public string CustomerPONumber { get; set; }
        public string RollNumber { get; set; }
        public string MaterialNumber { get; set; }
        public string CustomerPartNumber { get; set; }
        public int RollWeight { get; set; }
        public System.DateTime OrderDate { get; set; }
        public System.DateTime ShippedDate { get; set; }
        public System.DateTime ScheduleDeliveryDate { get; set; }
        public string Carrier { get; set; }
        public System.DateTime ReceivedDate { get; set; }
        public System.DateTime UsedDate { get; set; }
        public System.DateTime LastPhysicalDate { get; set; }
        public string ShipmentNumber { get; set; }
        public string DeliveryNumber { get; set; }
    }
}
